id: I39437394
source: null
source_file: null
initial_creation_type: input
imported: '2022-06-30T11:55:10.137356'
last_modified: '2022-06-30T11:55:10.137478'
parser: null
source_metadata:
  title: ༄། །བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པ་བཞུགས་སོ།
  language: bo
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
